import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>shrty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>shrty!</span>
        </h1>

        <p className={styles.description}>
          Paste your link and press the button{" "}
        </p>

        <form className={classNames(styles.form, "border")}>
          <input className={classNames(styles.input, "border")} type="text" />
          <button className={styles.button} type="submit">
            sbmit
          </button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          className={styles.link}
          href="https://github.com/fpetrakov/shrty"
          target="_blank"
          rel="noopener noreferrer"
        >
          Github
        </a>
      </footer>
    </div>
  );
}
